/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.InsertController;

/**
 *
 * @author saran
 */
public class AddTraveler extends javax.swing.JFrame {

    /**
     * Creates new form AddTraveler
     */
    public AddTraveler() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TravelerInfoText = new javax.swing.JLabel();
        nTravelerIdTxt = new javax.swing.JLabel();
        nTravelerNicTxt = new javax.swing.JLabel();
        nTravelerNameTxt = new javax.swing.JLabel();
        nTravelerContactTxt = new javax.swing.JLabel();
        nTravelerPassTxt = new javax.swing.JLabel();
        nTravelerPass = new javax.swing.JPasswordField();
        nTravelerContact = new javax.swing.JTextField();
        nTravelerName = new javax.swing.JTextField();
        nTravelerNic = new javax.swing.JTextField();
        nTravelerId = new javax.swing.JTextField();
        BackBtn = new javax.swing.JButton();
        ResteBtn = new javax.swing.JButton();
        createBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        minimizeBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        AddTravelerImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TravelerInfoText.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        TravelerInfoText.setForeground(new java.awt.Color(13, 63, 51));
        TravelerInfoText.setText("Add Traveler");
        jPanel1.add(TravelerInfoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        nTravelerIdTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        nTravelerIdTxt.setText("Traveler ID");
        jPanel1.add(nTravelerIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        nTravelerNicTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        nTravelerNicTxt.setText("National ID");
        jPanel1.add(nTravelerNicTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        nTravelerNameTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        nTravelerNameTxt.setText("Traveler Name");
        jPanel1.add(nTravelerNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        nTravelerContactTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        nTravelerContactTxt.setText("Phone No.");
        jPanel1.add(nTravelerContactTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        nTravelerPassTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        nTravelerPassTxt.setText("Password");
        jPanel1.add(nTravelerPassTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));

        nTravelerPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(nTravelerPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 290, -1));

        nTravelerContact.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(nTravelerContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 290, -1));

        nTravelerName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(nTravelerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 290, -1));

        nTravelerNic.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(nTravelerNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 290, -1));

        nTravelerId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(nTravelerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 290, -1));

        BackBtn.setBackground(new java.awt.Color(13, 63, 51));
        BackBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        BackBtn.setForeground(new java.awt.Color(234, 223, 186));
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        jPanel1.add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 90, -1));

        ResteBtn.setBackground(new java.awt.Color(13, 63, 51));
        ResteBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        ResteBtn.setForeground(new java.awt.Color(234, 223, 186));
        ResteBtn.setText("Reset");
        ResteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ResteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 90, -1));

        createBtn.setBackground(new java.awt.Color(13, 63, 51));
        createBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        createBtn.setForeground(new java.awt.Color(234, 223, 186));
        createBtn.setText("Create");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        jPanel1.add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, -1, -1));

        homeBtn.setBackground(new java.awt.Color(13, 63, 51));
        homeBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        homeBtn.setForeground(new java.awt.Color(234, 223, 186));
        homeBtn.setText("Home");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 90, -1));

        minimizeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        minimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseClicked(evt);
            }
        });
        jPanel1.add(minimizeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 20, 20));

        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
        });
        jPanel1.add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 20, 20));

        AddTravelerImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MainBackground.png"))); // NOI18N
        jPanel1.add(AddTravelerImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        TravelerInformation view = new TravelerInformation();
        view.setVisible(true);
    }//GEN-LAST:event_BackBtnActionPerformed

    private void ResteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResteBtnActionPerformed
        // TODO add your handling code here:
        clearField();
    }//GEN-LAST:event_ResteBtnActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        InsertController.AddTraveler(nTravelerId.getText(), nTravelerNic.getText(), nTravelerName.getText(), nTravelerContact.getText(), nTravelerPass.getText());
        setVisible(false);
    }//GEN-LAST:event_createBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        HomePage view = new HomePage();
        view.setVisible(true);
    }//GEN-LAST:event_homeBtnActionPerformed

    private void minimizeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(AdminLoginPage.ICONIFIED);
    }//GEN-LAST:event_minimizeBtnMouseClicked

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeBtnMouseClicked

    public void clearField(){
        nTravelerId.setText("");
        nTravelerNic.setText("");
        nTravelerName.setText("");
        nTravelerContact.setText("");
        nTravelerPass.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTraveler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTraveler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTraveler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTraveler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTraveler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddTravelerImg;
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton ResteBtn;
    private javax.swing.JLabel TravelerInfoText;
    private javax.swing.JButton closeBtn;
    private javax.swing.JButton createBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton minimizeBtn;
    private javax.swing.JTextField nTravelerContact;
    private javax.swing.JLabel nTravelerContactTxt;
    private javax.swing.JTextField nTravelerId;
    private javax.swing.JLabel nTravelerIdTxt;
    private javax.swing.JTextField nTravelerName;
    private javax.swing.JLabel nTravelerNameTxt;
    private javax.swing.JTextField nTravelerNic;
    private javax.swing.JLabel nTravelerNicTxt;
    private javax.swing.JPasswordField nTravelerPass;
    private javax.swing.JLabel nTravelerPassTxt;
    // End of variables declaration//GEN-END:variables
}
