/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.LoginController;

/**
 *
 * @author saran
 */
public class AdminLoginPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminLoginPage
     */
    public AdminLoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        minimizeBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        AdminLoginText = new javax.swing.JLabel();
        loginUserName = new javax.swing.JLabel();
        loginPW = new javax.swing.JLabel();
        userNameTF = new javax.swing.JTextField();
        pWTF = new javax.swing.JPasswordField();
        cancelBtn = new javax.swing.JButton();
        loginBtn = new javax.swing.JButton();
        ResteBtn = new javax.swing.JButton();
        AdminLoginImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimizeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        minimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseClicked(evt);
            }
        });
        jPanel1.add(minimizeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 20, 20));

        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
        });
        jPanel1.add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 20, 20));

        homeButton.setBackground(new java.awt.Color(13, 63, 51));
        homeButton.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        homeButton.setForeground(new java.awt.Color(234, 223, 186));
        homeButton.setText("Home");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 130, 40));

        AdminLoginText.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        AdminLoginText.setForeground(new java.awt.Color(13, 63, 51));
        AdminLoginText.setText("Admin Login");
        jPanel1.add(AdminLoginText, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        loginUserName.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        loginUserName.setText("User Name");
        jPanel1.add(loginUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        loginPW.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        loginPW.setText("Password");
        jPanel1.add(loginPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        userNameTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(userNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 280, -1));

        pWTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(pWTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 280, -1));

        cancelBtn.setBackground(new java.awt.Color(13, 63, 51));
        cancelBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(234, 223, 186));
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        jPanel1.add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));

        loginBtn.setBackground(new java.awt.Color(13, 63, 51));
        loginBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(234, 223, 186));
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        jPanel1.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 90, -1));

        ResteBtn.setBackground(new java.awt.Color(13, 63, 51));
        ResteBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        ResteBtn.setForeground(new java.awt.Color(234, 223, 186));
        ResteBtn.setText("Reset");
        ResteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ResteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 90, -1));

        AdminLoginImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MainBackground.png"))); // NOI18N
        jPanel1.add(AdminLoginImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(AdminLoginPage.ICONIFIED);
    }//GEN-LAST:event_minimizeBtnMouseClicked

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeBtnMouseClicked

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        HomePage view = new HomePage();
        view.setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        LoginController.Adminlogin(userNameTF.getText(), pWTF.getText(), this);
    }//GEN-LAST:event_loginBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        LoginPage view = new LoginPage();
        view.setVisible(true);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void ResteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResteBtnActionPerformed
        // TODO add your handling code here:
        clearField();
    }//GEN-LAST:event_ResteBtnActionPerformed

    private void clearField() {
        userNameTF.setText("");
        pWTF.setText("");
    }
  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AdminLoginPage().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminLoginImg;
    private javax.swing.JLabel AdminLoginText;
    private javax.swing.JButton ResteBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton closeBtn;
    private javax.swing.JButton homeButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel loginPW;
    private javax.swing.JLabel loginUserName;
    private javax.swing.JButton minimizeBtn;
    private javax.swing.JPasswordField pWTF;
    private javax.swing.JTextField userNameTF;
    // End of variables declaration//GEN-END:variables
}
