/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.EditController;
import Controller.UpdateController;
import Model.DBSearch;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author saran
 */
public class EditTraveler extends javax.swing.JFrame {

    /**
     * Creates new form EditTraveler
     */
    public EditTraveler() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        editTravelerText = new javax.swing.JLabel();
        travelerNewIdTxt = new javax.swing.JLabel();
        travelerIDtxt = new javax.swing.JLabel();
        travelerNameTxt = new javax.swing.JLabel();
        travelerContactTxt = new javax.swing.JLabel();
        travelerPassTxt = new javax.swing.JLabel();
        travelerPass = new javax.swing.JPasswordField();
        travelerContact = new javax.swing.JTextField();
        travelerName = new javax.swing.JTextField();
        travelerID = new javax.swing.JTextField();
        travelerNewId = new javax.swing.JTextField();
        cancelBtn = new javax.swing.JButton();
        ResteBtn = new javax.swing.JButton();
        okBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        travelerNIC = new javax.swing.JTextField();
        travelerNICtxt = new javax.swing.JLabel();
        minimizeBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        EditTravelerImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editTravelerText.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        editTravelerText.setForeground(new java.awt.Color(13, 63, 51));
        editTravelerText.setText("Edit Traveler");
        jPanel1.add(editTravelerText, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        travelerNewIdTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        travelerNewIdTxt.setText("Traveler New ID");
        jPanel1.add(travelerNewIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        travelerIDtxt.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        travelerIDtxt.setText("Traveler ID");
        jPanel1.add(travelerIDtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        travelerNameTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        travelerNameTxt.setText("First Name");
        jPanel1.add(travelerNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        travelerContactTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        travelerContactTxt.setText("Phone No.");
        jPanel1.add(travelerContactTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));

        travelerPassTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        travelerPassTxt.setText("Password");
        jPanel1.add(travelerPassTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        travelerPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(travelerPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 290, -1));

        travelerContact.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(travelerContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 290, -1));

        travelerName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        travelerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                travelerNameActionPerformed(evt);
            }
        });
        jPanel1.add(travelerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 290, -1));

        travelerID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(travelerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 290, -1));

        travelerNewId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(travelerNewId, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 290, -1));

        cancelBtn.setBackground(new java.awt.Color(13, 63, 51));
        cancelBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(234, 223, 186));
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        jPanel1.add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, -1, -1));

        ResteBtn.setBackground(new java.awt.Color(13, 63, 51));
        ResteBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        ResteBtn.setForeground(new java.awt.Color(234, 223, 186));
        ResteBtn.setText("Reset");
        ResteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ResteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 90, -1));

        okBtn.setBackground(new java.awt.Color(13, 63, 51));
        okBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        okBtn.setForeground(new java.awt.Color(234, 223, 186));
        okBtn.setText("Ok");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });
        jPanel1.add(okBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, 90, -1));

        searchBtn.setBackground(new java.awt.Color(13, 63, 51));
        searchBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(234, 223, 186));
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        jPanel1.add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, 90, -1));

        travelerNIC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(travelerNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 290, -1));

        travelerNICtxt.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        travelerNICtxt.setText("Traveler NIC");
        jPanel1.add(travelerNICtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        minimizeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        minimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseClicked(evt);
            }
        });
        jPanel1.add(minimizeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 20, 20));

        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
        });
        jPanel1.add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 20, 20));

        editBtn.setBackground(new java.awt.Color(13, 63, 51));
        editBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        editBtn.setForeground(new java.awt.Color(234, 223, 186));
        editBtn.setText("Edit");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });
        jPanel1.add(editBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 90, -1));

        EditTravelerImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MainBackground.png"))); // NOI18N
        jPanel1.add(EditTravelerImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        TravelerInformation view = new TravelerInformation();
        view.setVisible(true);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void ResteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResteBtnActionPerformed
        // TODO add your handling code here:
        clearField1();
    }//GEN-LAST:event_ResteBtnActionPerformed

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        // TODO add your handling code here:
        EditController.travelerEdit(travelerID.getText(),travelerNewId.getText(),travelerNIC.getText(),travelerName.getText(),travelerContact.getText(),travelerPass.getText());
        clearField1();
    }//GEN-LAST:event_okBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        ResultSet rs = new DBSearch().searchTrEdit(travelerID.getText());
        try { 
            if(rs.next() == false){
                JOptionPane.showMessageDialog(this,"Traveler Doesn't exist");
            }
            else{               
                travelerNewId.setText(rs.getString("TravelerID"));
                travelerNIC.setText(rs.getString("TravelerNIC"));
                travelerName.setText(rs.getString("TravelerName"));
                travelerContact.setText(rs.getString("TravelerContact"));
                travelerPass.setText(rs.getString("TravelerPassword"));            
            }    
        } 
        catch (SQLException ex) {
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void travelerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_travelerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_travelerNameActionPerformed

    private void minimizeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(AdminLoginPage.ICONIFIED);
    }//GEN-LAST:event_minimizeBtnMouseClicked

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeBtnMouseClicked

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        clearField();
    }//GEN-LAST:event_editBtnActionPerformed

    public void clearField(){
        travelerNewId.setText("");
        travelerNIC.setText("");
        travelerName.setText("");
        travelerContact.setText("");
        travelerPass.setText("");
    }
    
    public void clearField1(){
        travelerID.setText("");
        travelerNewId.setText("");
        travelerNIC.setText("");
        travelerName.setText("");
        travelerContact.setText("");
        travelerPass.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditTraveler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditTraveler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditTraveler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditTraveler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditTraveler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EditTravelerImg;
    private javax.swing.JButton ResteBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton closeBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel editTravelerText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton minimizeBtn;
    private javax.swing.JButton okBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField travelerContact;
    private javax.swing.JLabel travelerContactTxt;
    private javax.swing.JTextField travelerID;
    private javax.swing.JLabel travelerIDtxt;
    private javax.swing.JTextField travelerNIC;
    private javax.swing.JLabel travelerNICtxt;
    private javax.swing.JTextField travelerName;
    private javax.swing.JLabel travelerNameTxt;
    private javax.swing.JTextField travelerNewId;
    private javax.swing.JLabel travelerNewIdTxt;
    private javax.swing.JPasswordField travelerPass;
    private javax.swing.JLabel travelerPassTxt;
    // End of variables declaration//GEN-END:variables
}
