/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.EditController;
import Controller.InsertController;
import Model.DBSearch;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author saran
 */
public class EditGuide extends javax.swing.JFrame {

    public EditGuide() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        GuideInfoText = new javax.swing.JLabel();
        guideNewIdTxt = new javax.swing.JLabel();
        guideNICTxt = new javax.swing.JLabel();
        guideNameTxt = new javax.swing.JLabel();
        guideContactTxt = new javax.swing.JLabel();
        guidePassTxt = new javax.swing.JLabel();
        guidePass = new javax.swing.JPasswordField();
        guideContact = new javax.swing.JTextField();
        guideName = new javax.swing.JTextField();
        guideNIC = new javax.swing.JTextField();
        guideNewId = new javax.swing.JTextField();
        ResteBtn = new javax.swing.JButton();
        minimizeBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        vehicleNo = new javax.swing.JTextField();
        vehicleNoTxt = new javax.swing.JLabel();
        vehicleModelTxt = new javax.swing.JLabel();
        vehicleModel = new javax.swing.JTextField();
        priceForDay = new javax.swing.JTextField();
        priceForDayTxt = new javax.swing.JLabel();
        guideID = new javax.swing.JTextField();
        guideIDTxt1 = new javax.swing.JLabel();
        searchBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        okBtn = new javax.swing.JButton();
        AddGuideImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GuideInfoText.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        GuideInfoText.setForeground(new java.awt.Color(13, 63, 51));
        GuideInfoText.setText("Edit Guide");
        jPanel1.add(GuideInfoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        guideNewIdTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        guideNewIdTxt.setText("New ID");
        jPanel1.add(guideNewIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        guideNICTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        guideNICTxt.setText("National ID");
        jPanel1.add(guideNICTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        guideNameTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        guideNameTxt.setText("Guide Name");
        jPanel1.add(guideNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        guideContactTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        guideContactTxt.setText("Phone No.");
        jPanel1.add(guideContactTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        guidePassTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        guidePassTxt.setText("Password");
        jPanel1.add(guidePassTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        guidePass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(guidePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 210, -1));

        guideContact.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(guideContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 210, -1));

        guideName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(guideName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 210, -1));

        guideNIC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(guideNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 210, -1));

        guideNewId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        guideNewId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guideNewIdActionPerformed(evt);
            }
        });
        jPanel1.add(guideNewId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 210, -1));

        ResteBtn.setBackground(new java.awt.Color(13, 63, 51));
        ResteBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        ResteBtn.setForeground(new java.awt.Color(234, 223, 186));
        ResteBtn.setText("Reset");
        ResteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ResteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 90, -1));

        minimizeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        minimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseClicked(evt);
            }
        });
        jPanel1.add(minimizeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 20, 20));

        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
        });
        jPanel1.add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 20, 20));

        vehicleNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        vehicleNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleNoActionPerformed(evt);
            }
        });
        jPanel1.add(vehicleNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 210, -1));

        vehicleNoTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        vehicleNoTxt.setText("Vehicle No.");
        jPanel1.add(vehicleNoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, -1, -1));

        vehicleModelTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        vehicleModelTxt.setText("Vehicle Model");
        jPanel1.add(vehicleModelTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, -1, -1));

        vehicleModel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        vehicleModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleModelActionPerformed(evt);
            }
        });
        jPanel1.add(vehicleModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 210, -1));

        priceForDay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        priceForDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceForDayActionPerformed(evt);
            }
        });
        jPanel1.add(priceForDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 210, -1));

        priceForDayTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        priceForDayTxt.setText("Price for Day");
        jPanel1.add(priceForDayTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, -1, -1));

        guideID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        guideID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guideIDActionPerformed(evt);
            }
        });
        jPanel1.add(guideID, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 210, -1));

        guideIDTxt1.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        guideIDTxt1.setText("Guide ID");
        jPanel1.add(guideIDTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        searchBtn.setBackground(new java.awt.Color(13, 63, 51));
        searchBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(234, 223, 186));
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        jPanel1.add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 90, -1));

        cancelBtn.setBackground(new java.awt.Color(13, 63, 51));
        cancelBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(234, 223, 186));
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        jPanel1.add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, -1, -1));

        editBtn.setBackground(new java.awt.Color(13, 63, 51));
        editBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        editBtn.setForeground(new java.awt.Color(234, 223, 186));
        editBtn.setText("Edit");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });
        jPanel1.add(editBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 90, -1));

        okBtn.setBackground(new java.awt.Color(13, 63, 51));
        okBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        okBtn.setForeground(new java.awt.Color(234, 223, 186));
        okBtn.setText("Ok");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });
        jPanel1.add(okBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 90, -1));

        AddGuideImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MainBackground.png"))); // NOI18N
        jPanel1.add(AddGuideImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ResteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResteBtnActionPerformed
        // TODO add your handling code here:
        clearField1();
    }//GEN-LAST:event_ResteBtnActionPerformed

    private void minimizeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(AdminLoginPage.ICONIFIED);
    }//GEN-LAST:event_minimizeBtnMouseClicked

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeBtnMouseClicked

    private void guideNewIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guideNewIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guideNewIdActionPerformed

    private void vehicleNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicleNoActionPerformed

    private void vehicleModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicleModelActionPerformed

    private void priceForDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceForDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceForDayActionPerformed

    private void guideIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guideIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guideIDActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        ResultSet rs = new DBSearch().searchGdEdit(guideID.getText());
        try {
            if(rs.next() == false){
                JOptionPane.showMessageDialog(this,"Guide Doesn't exist");
            }
            else {
                guideNewId.setText(rs.getString("GuideID"));
                guideNIC.setText(rs.getString("GuideNIC"));
                guideName.setText(rs.getString("GuideName"));
                guideContact.setText(rs.getString("GuideContact"));
                guidePass.setText(rs.getString("GuidePassword"));
                vehicleNo.setText(rs.getString("VehicleNo"));
                vehicleModel.setText(rs.getString("VehicleModel"));

                // Extract and display PriceForDay with robust error handling
                try {
                    int priceForDayValue = rs.getInt("PriceForDay"); // Attempt direct integer retrieval
                    priceForDay.setText(String.valueOf(priceForDayValue)); // Display extracted value
                } catch (SQLException e) {
                    // Handle potential SQLException (e.g., column not found)
                    System.err.println("Error retrieving PriceForDay: " + e.getMessage());
                    priceForDay.setText("N/A (Error)"); // Display fallback value
                } catch (ClassCastException e) {
                    // Handle potential ClassCastException (if column type mismatch)
                    System.err.println("PriceForDay may not be an integer: " + e.getMessage());
                    priceForDay.setText("N/A (Invalid Type)"); // Display fallback value
                }
            }
        }
        catch (SQLException ex) {
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        GuideInformation view = new GuideInformation();
        view.setVisible(true);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        clearField();
    }//GEN-LAST:event_editBtnActionPerformed

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        // TODO add your handling code here:
        EditController.guideEdit(guideID.getText(),guideNewId.getText(),guideNIC.getText(),guideName.getText(),guideContact.getText(),guidePass.getText(), vehicleNo.getText(), vehicleModel.getText(), Integer.parseInt(priceForDay.getText()));
        clearField1();
    }//GEN-LAST:event_okBtnActionPerformed

    public void clearField(){
        guideNewId.setText("");
        guideNIC.setText("");
        guideName.setText("");
        guideContact.setText("");
        guidePass.setText("");
        vehicleNo.setText("");
        vehicleModel.setText("");
        priceForDay.setText("");
    }
    
    public void clearField1(){
        guideID.setText("");
        guideNewId.setText("");
        guideNIC.setText("");
        guideName.setText("");
        guideContact.setText("");
        guidePass.setText("");
        vehicleNo.setText("");
        vehicleModel.setText("");
        priceForDay.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditGuide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditGuide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditGuide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditGuide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditGuide().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddGuideImg;
    private javax.swing.JLabel GuideInfoText;
    private javax.swing.JButton ResteBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton closeBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JTextField guideContact;
    private javax.swing.JLabel guideContactTxt;
    private javax.swing.JTextField guideID;
    private javax.swing.JLabel guideIDTxt1;
    private javax.swing.JTextField guideNIC;
    private javax.swing.JLabel guideNICTxt;
    private javax.swing.JTextField guideName;
    private javax.swing.JLabel guideNameTxt;
    private javax.swing.JTextField guideNewId;
    private javax.swing.JLabel guideNewIdTxt;
    private javax.swing.JPasswordField guidePass;
    private javax.swing.JLabel guidePassTxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton minimizeBtn;
    private javax.swing.JButton okBtn;
    private javax.swing.JTextField priceForDay;
    private javax.swing.JLabel priceForDayTxt;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField vehicleModel;
    private javax.swing.JLabel vehicleModelTxt;
    private javax.swing.JTextField vehicleNo;
    private javax.swing.JLabel vehicleNoTxt;
    // End of variables declaration//GEN-END:variables
}
