/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.InsertController;
import Controller.LoginController;

/**
 *
 * @author saran
 */
public class GuideLoginPage extends javax.swing.JFrame {

    public GuideLoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        minimizeBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        GuideLoginText = new javax.swing.JLabel();
        loginUserName = new javax.swing.JLabel();
        loginPW = new javax.swing.JLabel();
        userNameTF = new javax.swing.JTextField();
        pWTF = new javax.swing.JPasswordField();
        cancelBtn = new javax.swing.JButton();
        loginBtn = new javax.swing.JButton();
        cancelBtn2 = new javax.swing.JButton();
        createBtn = new javax.swing.JButton();
        nGuideIdTxt = new javax.swing.JLabel();
        nGuideNicTxt = new javax.swing.JLabel();
        nGuideNameTxt = new javax.swing.JLabel();
        nGuideContactTxt = new javax.swing.JLabel();
        nGuidePassTxt = new javax.swing.JLabel();
        nGuideId = new javax.swing.JTextField();
        nGuideNic = new javax.swing.JTextField();
        nGuideName = new javax.swing.JTextField();
        nGuideContact = new javax.swing.JTextField();
        nGuidePass = new javax.swing.JPasswordField();
        nVehicleNoTxt = new javax.swing.JLabel();
        nVehicleModelTxt = new javax.swing.JLabel();
        nPriceForDayTxt = new javax.swing.JLabel();
        nVehicleNo = new javax.swing.JTextField();
        nVehicleModel = new javax.swing.JTextField();
        nPriceForDay = new javax.swing.JTextField();
        tCreateTxt = new javax.swing.JLabel();
        tLoginTxt = new javax.swing.JLabel();
        ResteBtn = new javax.swing.JButton();
        ResteBtn1 = new javax.swing.JButton();
        TravelerLoginImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimizeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        minimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseClicked(evt);
            }
        });
        jPanel1.add(minimizeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 20, 20));

        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
        });
        jPanel1.add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 20, 20));

        homeButton.setBackground(new java.awt.Color(13, 63, 51));
        homeButton.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        homeButton.setForeground(new java.awt.Color(234, 223, 186));
        homeButton.setText("Home");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 450, 90, 30));

        GuideLoginText.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        GuideLoginText.setForeground(new java.awt.Color(13, 63, 51));
        GuideLoginText.setText("Guide Login");
        jPanel1.add(GuideLoginText, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        loginUserName.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        loginUserName.setText("User Name");
        jPanel1.add(loginUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, -1, -1));

        loginPW.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        loginPW.setText("Password");
        jPanel1.add(loginPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, -1, -1));

        userNameTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(userNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 230, -1));

        pWTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(pWTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 230, -1));

        cancelBtn.setBackground(new java.awt.Color(13, 63, 51));
        cancelBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(234, 223, 186));
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        jPanel1.add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, -1, -1));

        loginBtn.setBackground(new java.awt.Color(13, 63, 51));
        loginBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(234, 223, 186));
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        jPanel1.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, 90, -1));

        cancelBtn2.setBackground(new java.awt.Color(13, 63, 51));
        cancelBtn2.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        cancelBtn2.setForeground(new java.awt.Color(234, 223, 186));
        cancelBtn2.setText("Cancel");
        cancelBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtn2ActionPerformed(evt);
            }
        });
        jPanel1.add(cancelBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, -1));

        createBtn.setBackground(new java.awt.Color(13, 63, 51));
        createBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        createBtn.setForeground(new java.awt.Color(234, 223, 186));
        createBtn.setText("Create");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        jPanel1.add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, -1, -1));

        nGuideIdTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        nGuideIdTxt.setForeground(new java.awt.Color(255, 255, 255));
        nGuideIdTxt.setText("Guide ID");
        jPanel1.add(nGuideIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 100, 20));

        nGuideNicTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        nGuideNicTxt.setForeground(new java.awt.Color(255, 255, 255));
        nGuideNicTxt.setText("National ID");
        jPanel1.add(nGuideNicTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 100, 20));

        nGuideNameTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        nGuideNameTxt.setForeground(new java.awt.Color(255, 255, 255));
        nGuideNameTxt.setText("User Name");
        jPanel1.add(nGuideNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 100, 20));

        nGuideContactTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        nGuideContactTxt.setForeground(new java.awt.Color(255, 255, 255));
        nGuideContactTxt.setText("Phone No.");
        jPanel1.add(nGuideContactTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 90, 20));

        nGuidePassTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        nGuidePassTxt.setForeground(new java.awt.Color(255, 255, 255));
        nGuidePassTxt.setText("Password");
        jPanel1.add(nGuidePassTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 80, 20));

        nGuideId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(nGuideId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 158, 280, -1));

        nGuideNic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(nGuideNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 280, -1));

        nGuideName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(nGuideName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 280, -1));

        nGuideContact.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(nGuideContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 280, -1));

        nGuidePass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(nGuidePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 280, -1));

        nVehicleNoTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        nVehicleNoTxt.setForeground(new java.awt.Color(255, 255, 255));
        nVehicleNoTxt.setText("Vehicle No");
        jPanel1.add(nVehicleNoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 100, 20));

        nVehicleModelTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        nVehicleModelTxt.setForeground(new java.awt.Color(255, 255, 255));
        nVehicleModelTxt.setText("Vehicle Model");
        jPanel1.add(nVehicleModelTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 130, 20));

        nPriceForDayTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        nPriceForDayTxt.setForeground(new java.awt.Color(255, 255, 255));
        nPriceForDayTxt.setText("Price for Day");
        jPanel1.add(nPriceForDayTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 110, 20));

        nVehicleNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(nVehicleNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 280, -1));

        nVehicleModel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(nVehicleModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 280, -1));

        nPriceForDay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(nPriceForDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 280, -1));

        tCreateTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        tCreateTxt.setForeground(new java.awt.Color(0, 102, 0));
        tCreateTxt.setText("Create Accout");
        jPanel1.add(tCreateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        tLoginTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        tLoginTxt.setForeground(new java.awt.Color(0, 102, 0));
        tLoginTxt.setText("Login");
        jPanel1.add(tLoginTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, -1, -1));

        ResteBtn.setBackground(new java.awt.Color(13, 63, 51));
        ResteBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        ResteBtn.setForeground(new java.awt.Color(234, 223, 186));
        ResteBtn.setText("Reset");
        ResteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ResteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 90, -1));

        ResteBtn1.setBackground(new java.awt.Color(13, 63, 51));
        ResteBtn1.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        ResteBtn1.setForeground(new java.awt.Color(234, 223, 186));
        ResteBtn1.setText("Reset");
        ResteBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResteBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(ResteBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, 90, -1));

        TravelerLoginImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LoginBackground.png"))); // NOI18N
        jPanel1.add(TravelerLoginImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(GuideLoginPage.ICONIFIED);
    }//GEN-LAST:event_minimizeBtnMouseClicked

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeBtnMouseClicked

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        HomePage view = new HomePage();
        view.setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        LoginController.Guidelogin(userNameTF.getText(), pWTF.getText());
        String username;
        username = userNameTF.getText();
        GuidePage.GetUserName(username);
        setVisible(false);
    }//GEN-LAST:event_loginBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        LoginPage view = new LoginPage();
        view.setVisible(true);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void cancelBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtn2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        LoginPage view = new LoginPage();
        view.setVisible(true);
    }//GEN-LAST:event_cancelBtn2ActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        InsertController.InsertGuide(nGuideId.getText(), nGuideNic.getText(), nGuideName.getText(), nGuideContact.getText(), nGuidePass.getText(), nVehicleNo.getText(), nVehicleModel.getText(), Integer.parseInt(nPriceForDay.getText()));
    }//GEN-LAST:event_createBtnActionPerformed

    private void ResteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResteBtnActionPerformed
        // TODO add your handling code here:
        clearField();
    }//GEN-LAST:event_ResteBtnActionPerformed

    private void ResteBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResteBtn1ActionPerformed
        // TODO add your handling code here:
        clearField1();
    }//GEN-LAST:event_ResteBtn1ActionPerformed

    public void clearField(){
        nGuideId.setText("");
        nGuideNic.setText("");
        nGuideName.setText("");
        nGuideContact.setText("");
        nGuidePass.setText("");
        nVehicleNo.setText("");
        nVehicleModel.setText("");
        nPriceForDay.setText("");
    }
    
    private void clearField1() {
        userNameTF.setText("");
        pWTF.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuideLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuideLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuideLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuideLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuideLoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GuideLoginText;
    private javax.swing.JButton ResteBtn;
    private javax.swing.JButton ResteBtn1;
    private javax.swing.JLabel TravelerLoginImg;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton cancelBtn2;
    private javax.swing.JButton closeBtn;
    private javax.swing.JButton createBtn;
    private javax.swing.JButton homeButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel loginPW;
    private javax.swing.JLabel loginUserName;
    private javax.swing.JButton minimizeBtn;
    private javax.swing.JTextField nGuideContact;
    private javax.swing.JLabel nGuideContactTxt;
    private javax.swing.JTextField nGuideId;
    private javax.swing.JLabel nGuideIdTxt;
    private javax.swing.JTextField nGuideName;
    private javax.swing.JLabel nGuideNameTxt;
    private javax.swing.JTextField nGuideNic;
    private javax.swing.JLabel nGuideNicTxt;
    private javax.swing.JPasswordField nGuidePass;
    private javax.swing.JLabel nGuidePassTxt;
    private javax.swing.JTextField nPriceForDay;
    private javax.swing.JLabel nPriceForDayTxt;
    private javax.swing.JTextField nVehicleModel;
    private javax.swing.JLabel nVehicleModelTxt;
    private javax.swing.JTextField nVehicleNo;
    private javax.swing.JLabel nVehicleNoTxt;
    private javax.swing.JPasswordField pWTF;
    private javax.swing.JLabel tCreateTxt;
    private javax.swing.JLabel tLoginTxt;
    private javax.swing.JTextField userNameTF;
    // End of variables declaration//GEN-END:variables
   
}