/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.UpdateController;
import java.awt.Color;
import javax.swing.JTextField;

/**
 *
 * @author saran
 */
public class GuidePage extends javax.swing.JFrame {

    static void GetUserName(String username) {
        welcomeName.setText("");
        welcomeName.setText("Hello " +username);
        welcomeName1.setText("Welcome to the RTD!");
    }

    /**
     * Creates new form GuidePage
     */
    public GuidePage() {
        initComponents();
        new UpdateController().updateTourViewForGd(guidePageTBL);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        minimizeBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        welcomeName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        guidePageTBL = new javax.swing.JTable();
        logOutBtn = new javax.swing.JButton();
        welcomeName1 = new javax.swing.JTextField();
        yourToursTxt = new javax.swing.JLabel();
        TravelerPageImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimizeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        minimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseClicked(evt);
            }
        });
        jPanel1.add(minimizeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 20, 20));

        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
        });
        jPanel1.add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 20, 20));

        welcomeName.setBackground(new java.awt.Color(246, 246, 242));
        welcomeName.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        welcomeName.setForeground(new java.awt.Color(13, 63, 51));
        welcomeName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        welcomeName.setBorder(null);
        welcomeName.setOpaque(false);
        welcomeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                welcomeNameActionPerformed(evt);
            }
        });
        jPanel1.add(welcomeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 300, -1));

        guidePageTBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        guidePageTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TourID", "TravelerID", "StartCity", "EndCity", "Locations", "Days", "Total Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(guidePageTBL);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 760, 250));

        logOutBtn.setBackground(new java.awt.Color(13, 63, 51));
        logOutBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        logOutBtn.setForeground(new java.awt.Color(234, 223, 186));
        logOutBtn.setText("Log Out");
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });
        jPanel1.add(logOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 430, 100, -1));

        welcomeName1.setBackground(new java.awt.Color(246, 246, 242));
        welcomeName1.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        welcomeName1.setForeground(new java.awt.Color(13, 63, 51));
        welcomeName1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        welcomeName1.setBorder(null);
        welcomeName1.setOpaque(false);
        welcomeName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                welcomeName1ActionPerformed(evt);
            }
        });
        jPanel1.add(welcomeName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 300, -1));

        yourToursTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        yourToursTxt.setText("Your Tours");
        jPanel1.add(yourToursTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        TravelerPageImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PageBackground2.png"))); // NOI18N
        jPanel1.add(TravelerPageImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(AdminLoginPage.ICONIFIED);
    }//GEN-LAST:event_minimizeBtnMouseClicked

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeBtnMouseClicked

    private void welcomeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_welcomeNameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_welcomeNameActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        GuideLoginPage view = new GuideLoginPage();
        view.setVisible(true);
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void welcomeName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_welcomeName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_welcomeName1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuidePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuidePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuidePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuidePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuidePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TravelerPageImg;
    private javax.swing.JButton closeBtn;
    private javax.swing.JTable guidePageTBL;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JButton minimizeBtn;
    private static javax.swing.JTextField welcomeName;
    private static javax.swing.JTextField welcomeName1;
    private javax.swing.JLabel yourToursTxt;
    // End of variables declaration//GEN-END:variables

}
