/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author saran
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loginPageText = new javax.swing.JLabel();
        adminLoginBtn = new javax.swing.JButton();
        travelerLoginBtn = new javax.swing.JButton();
        guideLoginBtn = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        minimizeBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        loginPageImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginPageText.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        loginPageText.setForeground(new java.awt.Color(13, 63, 51));
        loginPageText.setText("Login As");
        jPanel1.add(loginPageText, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        adminLoginBtn.setBackground(new java.awt.Color(13, 63, 51));
        adminLoginBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        adminLoginBtn.setForeground(new java.awt.Color(234, 223, 186));
        adminLoginBtn.setText("Admin");
        adminLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLoginBtnActionPerformed(evt);
            }
        });
        jPanel1.add(adminLoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 130, 40));

        travelerLoginBtn.setBackground(new java.awt.Color(13, 63, 51));
        travelerLoginBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        travelerLoginBtn.setForeground(new java.awt.Color(234, 223, 186));
        travelerLoginBtn.setText("Traveler");
        travelerLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                travelerLoginBtnActionPerformed(evt);
            }
        });
        jPanel1.add(travelerLoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 130, 40));

        guideLoginBtn.setBackground(new java.awt.Color(13, 63, 51));
        guideLoginBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        guideLoginBtn.setForeground(new java.awt.Color(234, 223, 186));
        guideLoginBtn.setText("Guide");
        guideLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guideLoginBtnActionPerformed(evt);
            }
        });
        jPanel1.add(guideLoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 130, 40));

        homeButton.setBackground(new java.awt.Color(13, 63, 51));
        homeButton.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        homeButton.setForeground(new java.awt.Color(234, 223, 186));
        homeButton.setText("Home");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 130, 40));

        minimizeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        minimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseClicked(evt);
            }
        });
        jPanel1.add(minimizeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 20, 20));

        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
        });
        jPanel1.add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 20, 20));

        loginPageImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LoginPage.png"))); // NOI18N
        jPanel1.add(loginPageImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        HomePage view = new HomePage();
        view.setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void minimizeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(LoginPage.ICONIFIED);
    }//GEN-LAST:event_minimizeBtnMouseClicked

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeBtnMouseClicked

    private void adminLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLoginBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        AdminLoginPage view = new AdminLoginPage();
        view.setVisible(true);
    }//GEN-LAST:event_adminLoginBtnActionPerformed

    private void travelerLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_travelerLoginBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        TravelerLoginPage view = new TravelerLoginPage();
        view.setVisible(true);
    }//GEN-LAST:event_travelerLoginBtnActionPerformed

    private void guideLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guideLoginBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        GuideLoginPage view = new GuideLoginPage();
        view.setVisible(true);
    }//GEN-LAST:event_guideLoginBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminLoginBtn;
    private javax.swing.JButton closeBtn;
    private javax.swing.JButton guideLoginBtn;
    private javax.swing.JButton homeButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loginPageImg;
    private javax.swing.JLabel loginPageText;
    private javax.swing.JButton minimizeBtn;
    private javax.swing.JButton travelerLoginBtn;
    // End of variables declaration//GEN-END:variables
}
