/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DeleteController;
import Controller.InsertController;
import Controller.UpdateController;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;

/**
 *
 * @author saran
 */
public class TravelerPage extends javax.swing.JFrame {

    static void GetUserName(String username) {
        welcomeName.setText("");
        welcomeName.setText("Hello " +username);
        welcomeName1.setText("Welcome to the RTD!");
    }
    

    public TravelerPage() {
        initComponents();
        new UpdateController().updateTourView(travelerPageTBL);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        minimizeBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        welcomeName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        travelerPageTBL = new javax.swing.JTable();
        ResteBtn = new javax.swing.JButton();
        createBtn = new javax.swing.JButton();
        GuidesBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();
        travelerIdTxt = new javax.swing.JLabel();
        travelerId = new javax.swing.JTextField();
        startCityTxt = new javax.swing.JLabel();
        startCity = new javax.swing.JTextField();
        endCityTxt = new javax.swing.JLabel();
        endCity = new javax.swing.JTextField();
        welcomeName1 = new javax.swing.JTextField();
        planAtourTxt = new javax.swing.JLabel();
        yourToursTxt = new javax.swing.JLabel();
        locationTxt = new javax.swing.JLabel();
        daysTxt = new javax.swing.JLabel();
        guideIdTxt = new javax.swing.JLabel();
        guideId = new javax.swing.JTextField();
        days = new javax.swing.JTextField();
        location = new javax.swing.JTextField();
        deleteBtn = new javax.swing.JButton();
        TravelerPageImg = new javax.swing.JLabel();
        TravelerPageText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimizeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        minimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseClicked(evt);
            }
        });
        jPanel1.add(minimizeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 20, 20));

        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
        });
        jPanel1.add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 20, 20));

        welcomeName.setBackground(new java.awt.Color(246, 246, 242));
        welcomeName.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        welcomeName.setForeground(new java.awt.Color(13, 63, 51));
        welcomeName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        welcomeName.setBorder(null);
        welcomeName.setOpaque(false);
        welcomeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                welcomeNameActionPerformed(evt);
            }
        });
        jPanel1.add(welcomeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 300, -1));

        travelerPageTBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        travelerPageTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TourID", "StartCity", "EndCity", "Locations", "Days", "GuideId", "Total Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(travelerPageTBL);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 760, 100));

        ResteBtn.setBackground(new java.awt.Color(13, 63, 51));
        ResteBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        ResteBtn.setForeground(new java.awt.Color(234, 223, 186));
        ResteBtn.setText("Reset");
        ResteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ResteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 380, 90, -1));

        createBtn.setBackground(new java.awt.Color(13, 63, 51));
        createBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        createBtn.setForeground(new java.awt.Color(234, 223, 186));
        createBtn.setText("Create");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        jPanel1.add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, 90, -1));

        GuidesBtn.setBackground(new java.awt.Color(13, 63, 51));
        GuidesBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        GuidesBtn.setForeground(new java.awt.Color(234, 223, 186));
        GuidesBtn.setText("Guides");
        GuidesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuidesBtnActionPerformed(evt);
            }
        });
        jPanel1.add(GuidesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, 100, -1));

        logOutBtn.setBackground(new java.awt.Color(13, 63, 51));
        logOutBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        logOutBtn.setForeground(new java.awt.Color(234, 223, 186));
        logOutBtn.setText("Log Out");
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });
        jPanel1.add(logOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, 100, -1));

        travelerIdTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        travelerIdTxt.setText("Your ID");
        jPanel1.add(travelerIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        travelerId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        travelerId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                travelerIdActionPerformed(evt);
            }
        });
        jPanel1.add(travelerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 210, -1));

        startCityTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        startCityTxt.setText("Start City");
        jPanel1.add(startCityTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        startCity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        startCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startCityActionPerformed(evt);
            }
        });
        jPanel1.add(startCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 210, -1));

        endCityTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        endCityTxt.setText("End City");
        jPanel1.add(endCityTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        endCity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        endCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endCityActionPerformed(evt);
            }
        });
        jPanel1.add(endCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 210, -1));

        welcomeName1.setBackground(new java.awt.Color(246, 246, 242));
        welcomeName1.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        welcomeName1.setForeground(new java.awt.Color(13, 63, 51));
        welcomeName1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        welcomeName1.setBorder(null);
        welcomeName1.setOpaque(false);
        welcomeName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                welcomeName1ActionPerformed(evt);
            }
        });
        jPanel1.add(welcomeName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 300, -1));

        planAtourTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        planAtourTxt.setForeground(new java.awt.Color(0, 102, 0));
        planAtourTxt.setText("Plan a Tour");
        jPanel1.add(planAtourTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 140, -1));

        yourToursTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        yourToursTxt.setForeground(new java.awt.Color(0, 102, 0));
        yourToursTxt.setText("Your Tours");
        jPanel1.add(yourToursTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        locationTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        locationTxt.setText("Locations");
        jPanel1.add(locationTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, -1, -1));

        daysTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        daysTxt.setText("No. Days");
        jPanel1.add(daysTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, -1, -1));

        guideIdTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        guideIdTxt.setText("GuideID");
        jPanel1.add(guideIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, -1, -1));

        guideId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        guideId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guideIdActionPerformed(evt);
            }
        });
        jPanel1.add(guideId, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 210, -1));

        days.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        days.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daysActionPerformed(evt);
            }
        });
        jPanel1.add(days, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, 210, -1));

        location.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationActionPerformed(evt);
            }
        });
        jPanel1.add(location, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 210, -1));

        deleteBtn.setBackground(new java.awt.Color(13, 63, 51));
        deleteBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(234, 223, 186));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, 100, -1));

        TravelerPageImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TravelerPageBackground.png"))); // NOI18N
        jPanel1.add(TravelerPageImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        TravelerPageText.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        TravelerPageText.setForeground(new java.awt.Color(13, 63, 51));
        TravelerPageText.setText("Traveler");
        jPanel1.add(TravelerPageText, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(AdminLoginPage.ICONIFIED);
    }//GEN-LAST:event_minimizeBtnMouseClicked

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeBtnMouseClicked

    private void welcomeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_welcomeNameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_welcomeNameActionPerformed

    private void ResteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResteBtnActionPerformed
        // TODO add your handling code here:
        clearField();
    }//GEN-LAST:event_ResteBtnActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        try {
            // TODO add your handling code here:
            InsertController.AddTour(travelerId.getText(), startCity.getText(), endCity.getText(), location.getText(), Integer.parseInt(days.getText()), guideId.getText());
        } catch (SQLException ex) {
            Logger.getLogger(TravelerPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        new UpdateController().updateTourView(travelerPageTBL);
        clearField();
    }//GEN-LAST:event_createBtnActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        TravelerLoginPage view = new TravelerLoginPage();
        view.setVisible(true);
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void travelerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_travelerIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_travelerIdActionPerformed

    private void startCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startCityActionPerformed

    private void endCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endCityActionPerformed

    private void welcomeName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_welcomeName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_welcomeName1ActionPerformed

    private void guideIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guideIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guideIdActionPerformed

    private void daysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daysActionPerformed

    private void locationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        new DeleteController().deleteTour(travelerPageTBL);
        new UpdateController().updateTourView(travelerPageTBL);
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void GuidesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuidesBtnActionPerformed
        // TODO add your handling code here:
        GuideForTrView view = new GuideForTrView();
        view.setVisible(true);
    }//GEN-LAST:event_GuidesBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TravelerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TravelerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TravelerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TravelerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TravelerPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GuidesBtn;
    private javax.swing.JButton ResteBtn;
    private javax.swing.JLabel TravelerPageImg;
    private javax.swing.JLabel TravelerPageText;
    private javax.swing.JButton closeBtn;
    private javax.swing.JButton createBtn;
    private javax.swing.JTextField days;
    private javax.swing.JLabel daysTxt;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField endCity;
    private javax.swing.JLabel endCityTxt;
    private javax.swing.JTextField guideId;
    private javax.swing.JLabel guideIdTxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField location;
    private javax.swing.JLabel locationTxt;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JButton minimizeBtn;
    private javax.swing.JLabel planAtourTxt;
    private javax.swing.JTextField startCity;
    private javax.swing.JLabel startCityTxt;
    private javax.swing.JTextField travelerId;
    private javax.swing.JLabel travelerIdTxt;
    private javax.swing.JTable travelerPageTBL;
    private static javax.swing.JTextField welcomeName;
    private static javax.swing.JTextField welcomeName1;
    private javax.swing.JLabel yourToursTxt;
    // End of variables declaration//GEN-END:variables

    private void clearField() {
        travelerId.setText("");
        startCity.setText("");
        endCity.setText("");
        location.setText("");
        days.setText("");
        guideId.setText("");
    }
}
