/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.InsertController;
import Controller.LoginController;
import java.awt.event.ActionEvent;
import javax.swing.JTextField;

/**
 *
 * @author saran
 */
public class TravelerLoginPage extends javax.swing.JFrame {

    public TravelerLoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        minimizeBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        TravelerLoginText = new javax.swing.JLabel();
        loginUserName = new javax.swing.JLabel();
        loginPW = new javax.swing.JLabel();
        userNameTF = new javax.swing.JTextField();
        pWTF = new javax.swing.JPasswordField();
        cancelBtn = new javax.swing.JButton();
        loginBtn = new javax.swing.JButton();
        cancelBtn2 = new javax.swing.JButton();
        ResteBtn = new javax.swing.JButton();
        createBtn = new javax.swing.JButton();
        nTravelerIdTxt = new javax.swing.JLabel();
        nTravelerNicTxt = new javax.swing.JLabel();
        nTravelerNameTxt = new javax.swing.JLabel();
        nTravelerContactTxt = new javax.swing.JLabel();
        nTravelerPassTxt = new javax.swing.JLabel();
        nTravelerId = new javax.swing.JTextField();
        nTravelerNic = new javax.swing.JTextField();
        nTravelerName = new javax.swing.JTextField();
        nTravelerContact = new javax.swing.JTextField();
        nTravelerPass = new javax.swing.JPasswordField();
        tCreateTxt = new javax.swing.JLabel();
        tLoginTxt = new javax.swing.JLabel();
        ResteBtn1 = new javax.swing.JButton();
        TravelerLoginImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimizeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        minimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseClicked(evt);
            }
        });
        jPanel1.add(minimizeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 20, 20));

        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
        });
        jPanel1.add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 20, 20));

        homeButton.setBackground(new java.awt.Color(13, 63, 51));
        homeButton.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        homeButton.setForeground(new java.awt.Color(234, 223, 186));
        homeButton.setText("Home");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 430, 90, 30));

        TravelerLoginText.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        TravelerLoginText.setForeground(new java.awt.Color(13, 63, 51));
        TravelerLoginText.setText("Traveler Login");
        jPanel1.add(TravelerLoginText, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        loginUserName.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        loginUserName.setText("User Name");
        jPanel1.add(loginUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, -1, -1));

        loginPW.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        loginPW.setText("Password");
        jPanel1.add(loginPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, -1, -1));

        userNameTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        userNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTFActionPerformed(evt);
            }
        });
        jPanel1.add(userNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 230, -1));

        pWTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(pWTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 230, -1));

        cancelBtn.setBackground(new java.awt.Color(13, 63, 51));
        cancelBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(234, 223, 186));
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        jPanel1.add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, -1, -1));

        loginBtn.setBackground(new java.awt.Color(13, 63, 51));
        loginBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(234, 223, 186));
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        jPanel1.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, 90, -1));

        cancelBtn2.setBackground(new java.awt.Color(13, 63, 51));
        cancelBtn2.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        cancelBtn2.setForeground(new java.awt.Color(234, 223, 186));
        cancelBtn2.setText("Cancel");
        cancelBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtn2ActionPerformed(evt);
            }
        });
        jPanel1.add(cancelBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, -1, -1));

        ResteBtn.setBackground(new java.awt.Color(13, 63, 51));
        ResteBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        ResteBtn.setForeground(new java.awt.Color(234, 223, 186));
        ResteBtn.setText("Reset");
        ResteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ResteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 90, -1));

        createBtn.setBackground(new java.awt.Color(13, 63, 51));
        createBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        createBtn.setForeground(new java.awt.Color(234, 223, 186));
        createBtn.setText("Create");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        jPanel1.add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, -1, -1));

        nTravelerIdTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        nTravelerIdTxt.setForeground(new java.awt.Color(255, 255, 255));
        nTravelerIdTxt.setText("Traveler ID");
        jPanel1.add(nTravelerIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        nTravelerNicTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        nTravelerNicTxt.setForeground(new java.awt.Color(255, 255, 255));
        nTravelerNicTxt.setText("National ID");
        jPanel1.add(nTravelerNicTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        nTravelerNameTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        nTravelerNameTxt.setForeground(new java.awt.Color(255, 255, 255));
        nTravelerNameTxt.setText("Your Name");
        jPanel1.add(nTravelerNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        nTravelerContactTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        nTravelerContactTxt.setForeground(new java.awt.Color(255, 255, 255));
        nTravelerContactTxt.setText("Phone No.");
        jPanel1.add(nTravelerContactTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        nTravelerPassTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        nTravelerPassTxt.setForeground(new java.awt.Color(255, 255, 255));
        nTravelerPassTxt.setText("Password");
        jPanel1.add(nTravelerPassTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        nTravelerId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(nTravelerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 290, -1));

        nTravelerNic.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(nTravelerNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 290, -1));

        nTravelerName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(nTravelerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 290, -1));

        nTravelerContact.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(nTravelerContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 290, -1));

        nTravelerPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(nTravelerPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 290, -1));

        tCreateTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        tCreateTxt.setForeground(new java.awt.Color(0, 102, 0));
        tCreateTxt.setText("Create Accout");
        jPanel1.add(tCreateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        tLoginTxt.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        tLoginTxt.setForeground(new java.awt.Color(0, 102, 0));
        tLoginTxt.setText("Login");
        jPanel1.add(tLoginTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, -1, -1));

        ResteBtn1.setBackground(new java.awt.Color(13, 63, 51));
        ResteBtn1.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        ResteBtn1.setForeground(new java.awt.Color(234, 223, 186));
        ResteBtn1.setText("Reset");
        ResteBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResteBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(ResteBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, 90, -1));

        TravelerLoginImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LoginBackground.png"))); // NOI18N
        jPanel1.add(TravelerLoginImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(TravelerLoginPage.ICONIFIED);
    }//GEN-LAST:event_minimizeBtnMouseClicked

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeBtnMouseClicked

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        HomePage view = new HomePage();
        view.setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        LoginController.Travelerlogin(userNameTF.getText(), pWTF.getText());
        String username;
        username = userNameTF.getText();
        TravelerPage.GetUserName(username);
        setVisible(false);
    }//GEN-LAST:event_loginBtnActionPerformed
        
    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        LoginPage view = new LoginPage();
        view.setVisible(true);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void cancelBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtn2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        LoginPage view = new LoginPage();
        view.setVisible(true);
    }//GEN-LAST:event_cancelBtn2ActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        InsertController.InsertTraveler(nTravelerId.getText(), nTravelerNic.getText(), nTravelerName.getText(), nTravelerContact.getText(), nTravelerPass.getText());
    }//GEN-LAST:event_createBtnActionPerformed

    private void ResteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResteBtnActionPerformed
        // TODO add your handling code here:
        clearField();
    }//GEN-LAST:event_ResteBtnActionPerformed

    private void ResteBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResteBtn1ActionPerformed
        // TODO add your handling code here:
        clearField1();
    }//GEN-LAST:event_ResteBtn1ActionPerformed

    private void userNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTFActionPerformed

    public void clearField(){
        nTravelerId.setText("");
        nTravelerNic.setText("");
        nTravelerName.setText("");
        nTravelerContact.setText("");
        nTravelerPass.setText("");
    }
    
    private void clearField1() {
        userNameTF.setText("");
        pWTF.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TravelerLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TravelerLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TravelerLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TravelerLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TravelerLoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ResteBtn;
    private javax.swing.JButton ResteBtn1;
    private javax.swing.JLabel TravelerLoginImg;
    private javax.swing.JLabel TravelerLoginText;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton cancelBtn2;
    private javax.swing.JButton closeBtn;
    private javax.swing.JButton createBtn;
    private javax.swing.JButton homeButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel loginPW;
    private javax.swing.JLabel loginUserName;
    private javax.swing.JButton minimizeBtn;
    private javax.swing.JTextField nTravelerContact;
    private javax.swing.JLabel nTravelerContactTxt;
    private javax.swing.JTextField nTravelerId;
    private javax.swing.JLabel nTravelerIdTxt;
    private javax.swing.JTextField nTravelerName;
    private javax.swing.JLabel nTravelerNameTxt;
    private javax.swing.JTextField nTravelerNic;
    private javax.swing.JLabel nTravelerNicTxt;
    private javax.swing.JPasswordField nTravelerPass;
    private javax.swing.JLabel nTravelerPassTxt;
    private javax.swing.JPasswordField pWTF;
    private javax.swing.JLabel tCreateTxt;
    private javax.swing.JLabel tLoginTxt;
    private javax.swing.JTextField userNameTF;
    // End of variables declaration//GEN-END:variables

}